### ISSUE TITLE
Order list of campaigns

### ISSUE THREAD

**Issue by apwasilewski** [mhendri/rsp_campaign_visualizer#32]
ORACLES_2016 is between ORACLES_2018 and ORACLES_2017.  The order should either be alphabetical or chronological.

**Comment by mhendri** [comment]
@Natalie611 the campaigns were previously in order - its possible that the branch we did not integrate has that code.

**Comment by mhendri** [comment]
Template code that builds this is logic-less. Ordered the directory.json alphabetically while it's getting created to resolve this issue.
